name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v2
      with:
        name: xzfc
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-shell -p hello --run hello
